server:
  port: 9000

spring:
  application:
    name: gulimall-order
  datasource:
    username: gulimall
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 127.0.0.1:8080

  redis:
    host: 127.0.0.1
    port: 6379

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  #\u8BBE\u7F6E\u5B9E\u4F53\u7C7B\u7684\u81EA\u589E\u4E3B\u952E
  global-config:
    db-config:
      id-type: auto



#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'