server:
  port: 12000

spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#    sentinel:
#      transport:
        #配置sentinel dashboard地址
#        dashboard: localhost:8080

  redis:
    host: 127.0.0.1
    port: 6379

#开启feign对sentinel的支持
#feign:
#  sentinel:
#    enabled: true
#
#  thymeleaf:
#    cache: false
#
  session:
    store-type: redis
logging:
  level:
    com.ycs.gulimall: debug
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
