server:
  port: 7000

spring:
  application:
    name: gulimall-ware
  datasource:
    username: gulimall
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#    sentinel:
#      transport:
#        #配置sentinel dashboard地址
#        dashboard: 127.0.0.1:8080

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.xunqi.gulimall: debug

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'